name: Continuous Deployment

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export PATH=$PATH:/usr/local/bin:/usr/bin:/bin
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          node -v
          npm -v
          pm2 -v
          cd ~/forum-api
          git pull origin main
          npm install
          npm run migrate up
          /home/ubuntu/.nvm/versions/node/v23.5.0/bin/pm2 restart forum-api
