name: Continuous Integration
 
on: 
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: ['20.x']
   
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.PG_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_DATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run migrations for main database
      run: npm run migrate up
      env:
        PGHOST: ${{ secrets.PG_HOST }}
        PGPORT: 5432
        PGUSER: ${{ secrets.PG_USERNAME }}
        PGPASSWORD: ${{ secrets.PG_PASSWORD }}
        PGDATABASE: ${{ secrets.PG_DATABASE }}

    - name: Create test database config
      run: |
        jq \
        '.username = env.PGUSER | .password = env.PGPASSWORD | .host = env.PGHOST | .database = env.PGDATABASE_TEST' \
        config/database/test-example.json > config/database/test.json
      env:
        PGUSER: ${{ secrets.PG_USERNAME }}
        PGPASSWORD: ${{ secrets.PG_PASSWORD }}
        PGHOST: ${{ secrets.PG_HOST }}
        PGDATABASE_TEST: ${{ secrets.PG_DATABASE_TEST }}

    - name: Run migrations for test database
      run: npm run migrate:test up
      env:
        PGHOST: ${{ secrets.PG_HOST }}
        PGPORT: 5432
        PGUSER: ${{ secrets.PG_USERNAME }}
        PGPASSWORD: ${{ secrets.PG_PASSWORD }}
        PGDATABASE: ${{ secrets.PG_DATABASE_TEST }}

    - name: Run tests
      run: npm run test
      env:
        CI: true
        HOST: ${{ secrets.HOST }}
        PORT: 5000
        PGHOST: ${{ secrets.PG_HOST }}
        PGPORT: 5432
        PGUSER: ${{ secrets.PG_USERNAME }}
        PGPASSWORD: ${{ secrets.PG_PASSWORD }}
        PGDATABASE: ${{ secrets.PG_DATABASE }}
        PGDATABASE_TEST: ${{ secrets.PG_DATABASE_TEST }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
        ACCESS_TOKEN_AGE: 3600
